### ISSUE TITLE
add phantomjs 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by anilreddy** [anthavio/phanbedder#5]
@anthavio 2 days back phantomjs 2.1.0 and 2.1.1 has been released can you please update the same in phanbedder.

**Comment by rosolko** [comment]
@anilreddy I already create pull request for supporting 2.1.1 version. Local tests is ok. Wait for response.

**Comment by anthavio** [comment]
Cool. I'll take a look on it tomorrow

**Comment by anthavio** [comment]
Sorry for delay guys. 
I've just tested on Windows 10, Mac OSX Captain and Linux (whatever distro and version is on build server) and test are passing everywhere.
Release build https://vanek.ci.cloudbees.com/job/phanbedder-release/4
Expect jars to be published to maven central repo in few hours.
Thank you @rosolko and PhantomJS team. Great work.
